[project]
name = "tflops"
version = "0.1.0"
description = "MPS/CUDA TFLOPs tests"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "torch>=2.8.0",
]
